export const GET_POSTS_ACTION = 'GET_POSTS_ACTION';
export const GET_POSTS_SUCCESSED_ACTION = 'GET_POSTS_SUCCESSED_ACTION';
export const GET_POSTS_FAILED_ACTION = 'GET_POSTS_FAILED_ACTION';

export const GET_POST_ACTION = 'GET_POST_ACTION';
export const GET_POST_SUCCESSED_ACTION = 'GET_POST_SUCCESSED_ACTION';
export const GET_POST_FAILED_ACTION = 'GET_POST_FAILED_ACTION';

export const CREATE_POST_ACTION = 'CREATE_POST_ACTION';
export const CREATE_POST_SUCCESSED_ACTION = 'CREATE_POST_SUCCESSED_ACTION';
export const CREATE_POST_FAILED_ACTION = 'CREATE_POST_FAILED_ACTION';

export const UPDATE_POST_ACTION = 'UPDATE_POST_ACTION';
export const UPDATE_POST_SUCCESSED_ACTION = 'UPDATE_POST_SUCCESSED_ACTION';
export const UPDATE_POST_FAILED_ACTION = 'UPDATE_POST_FAILED_ACTION';

export const DELETE_POST_ACTION = 'DELETE_POST_ACTION';
export const DELETE_POST_SUCCESSED_ACTION = 'DELETE_POST_SUCCESSED_ACTION';
export const DELETE_POST_FAILED_ACTION = 'DELETE_POST_FAILED_ACTION';
